# Generated by Django 5.0.4 on 2024-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(db_column='ID_EVENEMENT', primary_key=True, serialize=False)),
                ('titre', models.CharField(db_column='TITRE', max_length=200)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('lieu', models.CharField(blank=True, db_column='LIEU', max_length=200, null=True)),
                ('date_evenement', models.DateTimeField(db_column='DATE_EVENEMENT')),
                ('capacite', models.IntegerField(db_column='CAPACITE')),
                ('programme', models.TextField(blank=True, db_column='PROGRAMME', null=True)),
                ('image', models.CharField(blank=True, db_column='IMAGE', max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_column='DATE_CREATION', null=True)),
            ],
            options={
                'db_table': 'evenement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SInscrireEvent',
            fields=[
                ('id_inscrire', models.AutoField(db_column='ID_INSCRIRE', primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, db_column='DATE_INSCRIPTION', null=True)),
            ],
            options={
                'db_table': 's_inscrire_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(db_column='ID_UTILISATEUR', primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(db_column='NOM_UTILISATEUR', max_length=100)),
                ('email_utilisateur', models.CharField(db_column='EMAIL_UTILISATEUR', max_length=150, unique=True)),
                ('mdp_utilisateur', models.CharField(db_column='MDP_UTILISATEUR', max_length=255)),
                ('role', models.CharField(db_column='ROLE', max_length=12)),
                ('date_creation', models.DateTimeField(blank=True, db_column='DATE_CREATION', null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
    ]
