# Generated by Django 5.0.4 on 2024-12-05 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_evenement', models.AutoField(db_column='ID_EVENEMENT', primary_key=True, serialize=False)),
                ('titre', models.TextField(blank=True, db_column='TITRE', null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('lieu', models.TextField(blank=True, db_column='LIEU', null=True)),
                ('date_evenement', models.DateField(blank=True, db_column='DATE_EVENEMENT', null=True)),
                ('date_creation', models.DateField(db_column='DATE_CREATION', default=django.utils.timezone.now)),
                ('capacite', models.IntegerField(blank=True, db_column='CAPACITE', null=True)),
                ('programme', models.TextField(blank=True, db_column='PROGRAMME', null=True)),
                ('image', models.ImageField(blank=True, db_column='IMAGE', null=True, upload_to='img/')),
            ],
            options={
                'db_table': 'evenement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscrire',
            fields=[
                ('id_evenement', models.IntegerField(db_column='ID_EVENEMENT', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inscrire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisateur',
            fields=[
                ('id_organisateur', models.AutoField(db_column='ID_ORGANISATEUR', primary_key=True, serialize=False)),
                ('nom_organisateur', models.TextField(blank=True, db_column='NOM_ORGANISATEUR', null=True)),
                ('email_organisateur', models.TextField(blank=True, db_column='EMAIL_ORGANISATEUR', null=True)),
                ('mdp_organisateur', models.TextField(blank=True, db_column='MDP_ORGANISATEUR', null=True)),
                ('isorgnisateur', models.IntegerField(blank=True, db_column='ISORGNISATEUR', null=True)),
            ],
            options={
                'db_table': 'organisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id_participant', models.AutoField(db_column='ID_PARTICIPANT', primary_key=True, serialize=False)),
                ('nom_participant', models.TextField(blank=True, db_column='NOM_PARTICIPANT', null=True)),
                ('email_participant', models.TextField(blank=True, db_column='EMAIL_PARTICIPANT', null=True)),
                ('mdp_participant', models.TextField(blank=True, db_column='MDP_PARTICIPANT', null=True)),
                ('isorganisteur', models.IntegerField(blank=True, db_column='ISORGANISTEUR', null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
