# Generated by Django 5.0.4 on 2024-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SInscrireEvent',
            fields=[
                ('id_inscrire', models.AutoField(db_column='ID_INSCRIRE', primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, db_column='DATE_INSCRIPTION', null=True)),
            ],
            options={
                'db_table': 's_inscrire_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(db_column='ID_UTILISATEUR', primary_key=True, serialize=False)),
                ('nom_utilisateur', models.CharField(db_column='NOM_UTILISATEUR', max_length=100)),
                ('email_utilisateur', models.CharField(db_column='EMAIL_UTILISATEUR', max_length=150, unique=True)),
                ('mdp_utilisateur', models.CharField(db_column='MDP_UTILISATEUR', max_length=255)),
                ('role', models.CharField(db_column='ROLE', max_length=12)),
                ('date_creation', models.DateTimeField(blank=True, db_column='DATE_CREATION', null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Inscrire',
        ),
        migrations.DeleteModel(
            name='Organisateur',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
